// Filename: \\SourceXI083\Unit_4\U4Chap04\LOGFUN.CPP
// Demonstration for the use of logarithmic and exponential functions
//1. exp(x). 2. log(x). 3. log10(x).
#include <iostream.h>
#include <math.h>
void logfun()
{
	int x = 1;
	cout << "The natural logarithm of 10 is : " << exp(x);
	cout << "\nThe natural logarithm of 10 is : " << log(x);
	cout << "\nThe base-10 logarithm of 10 is : " << log10(x);
}
